### ISSUE TITLE
Can't fuse yaml file containing @

### ISSUE THREAD

**Issue by marcoxsurf** [edgelaboratories/fusion#68] opened 2023-01-05 16:42 UTC
If a yaml contains the '@' it won't be fused.
The program exit with a failing status and the following message: "failed to load the input files: yaml: line 146: found character that cannot start any token"

**Comment by vthiery** [comment] 2023-01-24 06:24
Hello @marcoxsurf and sorry for not reverting back earlier on this issue.

I think I could reproduce your error and I believe it's simply due to invalid Yaml syntax.
Typically, something like
```yml
key1: 1
key2: @lb3rt0
```
won't be valid and will indeed trigger the error you mentioned.
If you quote the value, it should work fine:
```yml
key1: 1
key2: "@lb3rt0"
```
See https://github.com/edgelaboratories/fusion/pull/71 

Does it explain your issue?

**Comment by vthiery** [comment] 2023-02-20 11:50
Closing this issue as the matter seems resolved. Feel free to reopen if needed.

**Closed by vthiery** 2023-02-20 11:50 UTC
